
/*********************************************************************
 * This file is automatically generated by mmir-plugins-export tools *
 *         Do not modify: ANY CHANGES WILL GET DISCARED              *
 *********************************************************************/

module.exports = {
  pluginName: "ttsNuanceXhr",
  config: [
    /** OPTIONAL
     * [custom option]
     * if format is 'wav' or 'pcm', the sampling rate (Hz) for the audio
     * (otherwise ignored).
     * @type 8000 | 16000 | 22000
     * @default 8000
     */
    "sampleRate",
    /** OPTIONAL
     * [custom option]
     * format for the synthesized audio
     * NOTE: 'pcm' and 'wav' are synonymous
     * @type 'mp3' | 'wav' | 'pcm'
     * @default "mp3"
     */
    "format",
    /** credentials application key (MUST be set via configuration or options) */
    "appKey",
    /** credentials application ID (MUST be set via configuration or options) */
    "appId",
    /**
     * the plugin type
     * @default "tts"
     */
    "type",
    /** the plugin/module which which will load/use this specific TTS implementation
     * @default mmir-plugin-tts-core-xhr.js
     */
    "mod"
  ],
  defaultValues: {
    sampleRate: 8000,
    format: "mp3",
    type: "tts",
    mod: "mmir-plugin-tts-core-xhr.js"
  },
  speechConfig: [
    /** OPTIONAL
     * a specific voice for TTS
     * @type string
     */
    "voice",
    /** OPTIONAL
     * the language/country for TTS
     * @type string
     */
    "language"
  ],
  remoteUrls: {
    baseUrl: "https://tts.nuancemobility.net"
  }
};
