
/*********************************************************************
 * This file is automatically generated by mmir-plugins-export tools *
 *         Do not modify: ANY CHANGES WILL GET DISCARED              *
 *********************************************************************/

module.exports = {
  pluginName: "ttsNuanceXhr",
  config: [
    /** OPTIONAL
     * [custom option]
     * if format is 'wav' or 'pcm', the sampling rate (Hz) for the audio
     * (otherwise ignored).
     * @type 8000 | 16000 | 22000
     * @default 8000
     */
    "sampleRate",
    /** OPTIONAL
     * [custom option]
     * format for the synthesized audio
     * NOTE: 'pcm' and 'wav' are synonymous
     * @type 'mp3' | 'wav' | 'pcm'
     * @default "mp3"
     */
    "format",
    /** OPTIONAL
     * a specific voice for TTS
     * @type string
     */
    "voice",
    /** OPTIONAL
     * the language/country for TTS
     * @type string
     */
    "language"
  ],
  remoteUrls: {
    baseUrl: "https://tts.nuancemobility.net"
  }
};
